### ISSUE TITLE
Wrap "Identity" Field in identities

### ISSUE THREAD

**Issue by fkreiner** [fabXlabs/fabX#209]

**Comment by sschaeffner** [comment]
Context?

**Comment by fkreiner** [comment]
Long Webauthn IDs can increase the width of the "Identity" field to a point where the "Delete" button is pushed out of view on normal displays. This requires horizontal scrolling to delete the Identiy

**Comment by sschaeffner** [comment]
Seems to have been fixed by a primeng update
