### ISSUE TITLE
Add reason for disabled tools

### ISSUE THREAD

**Issue by fkreiner** [fabXlabs/fabX#210]
Rename property, invert logic, add locked reason. 
Is consistent with user locking

**Comment by sschaeffner** [comment]
I don't like calling it `locked` for a tool. I'd be fine with, e.g., `disabled`. That's, however, kind of an anti-pattern (i.e., having a checkbox which is checked/enabled would disable the tool).

**Comment by fkreiner** [comment]
Guess you are right. A reason for disabling the tool would still be nice.
